### ISSUE TITLE
[BUG] First-Person Hand Moves Down in World Space Instead of Screen Space

### ISSUE THREAD

**Issue by Novaenia** [KrLite/Faded-Widgets#3]
looks especially bad if you are looking down when you toggle F1
![POQ47T](https://github.com/user-attachments/assets/ae6e497d-0191-4d9f-a1ea-5461ad9ce3eb)

**Comment by KrLite** [comment]
Thanks for reporting! Fixed in [`2.2.0`](https://modrinth.com/mod/faded-widgets/version/2.2.0-fabric1.21).

This bug happens only on **Minecraft** `1.20.5+`. Remember to provide your game version next time submitting an issue in order to make your descriptions clearer. **Or, why don't you just fill out a [Bug Report?](https://github.com/KessokuTeaTime/Faded-Widgets/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml&title=%5BBUG%5D%3A+)**
